name: mcvae
channels:
- pytorch
- conda-forge # nibabel, nilearn
- defaults
dependencies:
- python=3
- numpy
- matplotlib=2.*
- scipy
- pandas
- ipython
- jupyter
- pytorch
- torchvision
- torchaudio
- cpuonly
- scikit-learn
- nibabel
- nilearn
- xlrd  # allows pandas to read excel files
- openpyxl  # allows pandas to write excel files
- natsort
